stages:
  - test
  - notify

run_tests:
  stage: test
  image: gradle:8.5-jdk17
  script:
    - gradle clean test
    - gradle allureReport
  artifacts:
    when: always
    paths:
      - build/test-results/test
      - build/allure-report
    reports:
      junit: build/test-results/test/TEST-*.xml

notify_telegram:
  stage: notify
  image: openjdk:17
  dependencies:
    - run_tests
  before_script:
    - apt-get update -y && apt-get install -y zip unzip curl
    - chmod +x ci/send_telegram.sh
  script:
    - ./ci/send_telegram.sh
  when: always
